# 59 Fs and a 6
COMMIT_TH = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6

# 61 Fs
REINF_TH = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

SWITCH_TH = 0

PORT = 5600

CANCEL_BLOCK_MIN_RANGE = 2

CANCEL_BLOCK_MAX_RANGE = 20

REINF_TIMEOUT = 1.5

COMMIT_TIMEOUT = 10

DELIVERY_DELAY = 0

CLEAN_PREVIOUS_BLOCKS = 100

PROPOSAL_TAG = "proposal"

COMMIT_TAG = "commit"

PROPOSAL_COMMIT_TAG = "proposal_commit"

REINFORCEMENT_TAG = "reinforcement"

TRANSACTION_TAG = "transaction"

MALICIOUS_PROPOSAL_AGREEMENT_TAG = "malicious_proposal_agreement"
