# 59 Fs and a 6
COMMIT_TH = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6

# 60 Fs
REINF_TH = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

SWITCH_TH = 0

CANCEL_PARTICULAR_BLOCK_TH = 60

PORT = 5600

CANCEL_BLOCK_MIN_RANGE = 2

CANCEL_BLOCK_MAX_RANGE = 4

TRANSACTION_INTERVAL = 3

REINF_TIMEOUT = 1.5

COMMIT_TIMEOUT = 10

DELIVERY_DELAY = 0

CLEAN_PREVIOUS_BLOCKS = 100

PROPOSAL_TAG = "proposal"

COMMIT_TAG = "commit"

PROPOSAL_COMMIT_TAG = "proposal_commit"

REINFORCEMENT_TAG = "reinforcement"

REINFORCEMENT_INF_TAG = "reinforcement_information"

TRANSACTION_TAG = "transaction"

MALICIOUS_PROPOSAL_AGREEMENT_TAG = "malicious_proposal_agreement"
